### ISSUE TITLE
第一届“小浣熊杯”

### ISSUE THREAD

**Issue by zccrs** [linuxdeepin/.bug-game#1]
## 举办时间

2023年3月7日 10:00 - 18:00 - 2023年3月8日 9:00 - 17：00 (+08时区)

## 看板

https://github.com/orgs/linuxdeepin/projects/26

## 即时聊天群

群名：“第一届小浣熊杯”

### 进击的小浣熊。队长 @BLumia 
@Decodetalkers @SuperEffie @Zeno-sole @BLumia @tsic404 @hudeng-go 

### 呆呆鹅。队长 @myml 
@xzl01 @asterwyx @myml @ArchieMeng @18202781743 @vivianxf 

### 修bug。队长 @justforlxz 
@luodeepin @ComixHe @justforlxz @FeiWang1119 @zsien @wineee 

### bug收割小分队。队长 @dengbo11 
@kamiyadm @black-desk @dengbo11 @xuqi27837288 @l631197874

**Comment by tsic404** [comment]
> 2023年7月7日 10:00 - 18:00 - 2023年7月8日 9:00 - 11：00 (+08时区)

时间是不是错了？7月？

**Comment by zccrs** [comment]
> > 2023年7月7日 10:00 - 18:00 - 2023年7月8日 9:00 - 11：00 (+08时区)
> 
> 时间是不是错了？7月？

已修改

**Comment by myml** [comment]
呆呆鹅=>DDE

**Comment by zccrs** [comment]
比赛过程截图记录：

![image](https://user-images.githubusercontent.com/13449038/223312422-7c2d02f0-7318-49d0-bcb0-124e5bd835d7.png)

![image](https://user-images.githubusercontent.com/13449038/223312494-6039b4a2-309a-44be-a8ac-61edffa9f963.png)

![image](https://user-images.githubusercontent.com/13449038/223312542-6cb48f79-af50-4696-9ded-0fa85635ff14.png)

![image](https://user-images.githubusercontent.com/13449038/223312582-f9574a65-5f04-4a24-b881-c98c8636aff2.png)

![image](https://user-images.githubusercontent.com/13449038/223312619-d7c75606-a0ac-4f54-87b4-21d2141b3696.png)

![image](https://user-images.githubusercontent.com/13449038/223312683-ca3a2473-164e-4384-8fb2-6bef776422af.png)

**Comment by zccrs** [comment]
实况：呆呆鹅为 https://github.com/linuxdeepin/developer-center/issues/3674 提交了 PR

**Comment by zccrs** [comment]
当前状态：
1. 进击的小浣熊队已经修复2个issue，另外有一个在测试中
2. bug收割小分队有1个issue已提交PR
3. 呆呆鹅对有1个issue已提交PR
4. 修bug对有1个issue在测试中

**Comment by zccrs** [comment]
当前状态：

总共修复了 7 个Bug（已测试通过），其中“进击的小浣熊”队修复了3个，“修bug”队修复了4个。

**Comment by zccrs** [comment]
当前状态：“修bug”队领先，“进击的小浣熊”则紧随其后，双方战况焦灼。“bug收割小分队”、“呆呆鹅”也在奋力追赶。

![image](https://user-images.githubusercontent.com/13449038/223640001-78314c59-9a8a-4ea1-9130-34b7a5c34adc.png)

![image](https://user-images.githubusercontent.com/13449038/223640047-1845b23c-0542-4524-a5d7-d9df9cbe5c56.png)

![image](https://user-images.githubusercontent.com/13449038/223640105-c1397cac-ffc1-48aa-b365-53d24a62d9ea.png)

![image](https://user-images.githubusercontent.com/13449038/223640171-12488035-0972-4570-ad05-38472fe4c121.png)

**Comment by zccrs** [comment]
结束时的状态：
![image](https://user-images.githubusercontent.com/13449038/223669395-9b3922fe-9c16-48c7-aef3-4ee497592aca.png)
![image](https://user-images.githubusercontent.com/13449038/223669441-5fc8ee9c-2fbb-4f23-9661-ee043df52b84.png)
![image](https://user-images.githubusercontent.com/13449038/223669511-ebcea01b-61cc-439a-b091-27e954a8933a.png)
![image](https://user-images.githubusercontent.com/13449038/223669593-848a264b-ddf5-4d2f-b891-e74379041d52.png)

**Comment by zccrs** [comment]
“第一届小浣熊杯大赛“于 2023 年 3 月 8 号 17: 00 正式结束。本次共有四支参赛队伍：
* 进击的小浣熊，队长 @BLumia
* 呆呆鹅，队长 @myml
* 修bug，队长 @justforlxz
* bug收割小分队，队长 @dengbo11

## 比赛结果
历时2天左右，所有队伍共修复 __42__ 个[Issues](https://github.com/orgs/linuxdeepin/projects/26/views/2)。其中 __进击的小浣熊__ 队共修复15个Issues，承担了10个Issues的测试任务。总积分 18.333，人均积分第一，获得第一届小浣熊杯 __大赛冠军__ 。

## 本届奖杯设计

![01404da7d3dde5c55b34e2ee5f860a3a(1)](https://user-images.githubusercontent.com/13449038/223905710-35b6f128-82d8-4222-82c6-06a0cf83078d.jpg)

## 冠军团队
![79e8aa0cbdf0d8a00150796e49c204e9](https://user-images.githubusercontent.com/13449038/223905944-e8b68703-a65f-4478-80e5-ceaa2834fb3a.jpg)
![86a079cb34111f4e68e011ba6085088e](https://user-images.githubusercontent.com/13449038/223905986-7b0e58b1-61f8-4428-9b83-b9cdf8b5e19b.jpg)
![691eccc5743b983fc36e61124bf4de85](https://user-images.githubusercontent.com/13449038/223905996-83119a2a-3b4b-4f5c-b301-001066680254.jpg)
![7570225ed1d3dd223aa72bce5589da3b](https://user-images.githubusercontent.com/13449038/223906005-7919a429-02bf-49d9-940f-39955d4a950c.jpg)
![c77de6de3da2e2716b83f3bbcfa5e3bc](https://user-images.githubusercontent.com/13449038/223906023-d251cd49-6efd-4dc1-a223-2151c818397d.jpg)
![e5e255648c61813499fdeabfe38835d2](https://user-images.githubusercontent.com/13449038/223906034-6c27fd2b-ce15-491b-8fc4-c208984ea206.jpg)
![image](https://user-images.githubusercontent.com/10095765/224207416-e1fa516d-8993-4d1c-8d1f-81114c0766ce.png)
<img width="1033" alt="企业微信截图_e137e6fb-21d9-4c5a-a21e-0afe87cac03e" src="https://user-images.githubusercontent.com/13449038/223911631-376c0d58-17a5-4401-843d-414dc287b7be.png">
